// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AWSService provides AWS operations to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetActiveProfile returns the currently active profile
 * @returns {$CancellablePromise<string>}
 */
export function GetActiveProfile() {
    return $Call.ByID(1237105474);
}

/**
 * GetCredentialExpiry returns credential expiry time
 * @param {string} profileName
 * @returns {$CancellablePromise<string>}
 */
export function GetCredentialExpiry(profileName) {
    return $Call.ByID(3196807213, profileName);
}

/**
 * GetDefaultRegion returns the default region
 * @returns {$CancellablePromise<string>}
 */
export function GetDefaultRegion() {
    return $Call.ByID(2424467084);
}

/**
 * GetProfiles returns all AWS profiles
 * @returns {$CancellablePromise<$models.ProfileInfo[]>}
 */
export function GetProfiles() {
    return $Call.ByID(1002264457).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetProfilesByStartURL groups profiles by SSO start URL
 * @returns {$CancellablePromise<{ [_: string]: $models.ProfileInfo[] }>}
 */
export function GetProfilesByStartURL() {
    return $Call.ByID(2011578941).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetSSOProfiles returns only SSO-enabled profiles
 * @returns {$CancellablePromise<$models.ProfileInfo[]>}
 */
export function GetSSOProfiles() {
    return $Call.ByID(3937322352).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetShellExport returns shell export commands for a profile
 * @param {string} profileName
 * @param {string} shell
 * @returns {$CancellablePromise<string>}
 */
export function GetShellExport(profileName, shell) {
    return $Call.ByID(1337, profileName, shell);
}

/**
 * GetStartURLs returns unique SSO start URLs
 * @returns {$CancellablePromise<string[]>}
 */
export function GetStartURLs() {
    return $Call.ByID(4012788087).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * IsLoggedIn checks if SSO session is valid
 * @param {string} profileName
 * @returns {$CancellablePromise<boolean>}
 */
export function IsLoggedIn(profileName) {
    return $Call.ByID(4145962856, profileName);
}

/**
 * Login initiates SSO login for a profile
 * @param {string} profileName
 * @returns {$CancellablePromise<void>}
 */
export function Login(profileName) {
    return $Call.ByID(3148061642, profileName);
}

/**
 * LoginAndSwitch logs in and switches to a profile
 * @param {string} profileName
 * @returns {$CancellablePromise<void>}
 */
export function LoginAndSwitch(profileName) {
    return $Call.ByID(23682971, profileName);
}

/**
 * Logout clears SSO session for a profile
 * @param {string} profileName
 * @returns {$CancellablePromise<void>}
 */
export function Logout(profileName) {
    return $Call.ByID(2622971395, profileName);
}

/**
 * RefreshCredentials refreshes credentials for a profile
 * @param {string} profileName
 * @returns {$CancellablePromise<void>}
 */
export function RefreshCredentials(profileName) {
    return $Call.ByID(2594442442, profileName);
}

/**
 * SwitchProfile switches to a different AWS profile
 * @param {string} profileName
 * @returns {$CancellablePromise<void>}
 */
export function SwitchProfile(profileName) {
    return $Call.ByID(2076345322, profileName);
}

/**
 * ValidateProfile validates a profile configuration
 * @param {string} profileName
 * @returns {$CancellablePromise<void>}
 */
export function ValidateProfile(profileName) {
    return $Call.ByID(1565608476, profileName);
}

// Private type creation functions
const $$createType0 = $models.ProfileInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = $Create.Array($Create.Any);
