// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ProfileInfo contains profile information for the frontend
 */
export class ProfileInfo {
    /**
     * Creates a new ProfileInfo instance.
     * @param {Partial<ProfileInfo>} [$$source = {}] - The source object to create the ProfileInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("region" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["region"] = "";
        }
        if (!("ssoStartUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ssoStartUrl"] = "";
        }
        if (!("ssoRegion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ssoRegion"] = "";
        }
        if (!("ssoAccountId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ssoAccountId"] = "";
        }
        if (!("ssoRoleName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ssoRoleName"] = "";
        }
        if (!("isSso" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isSso"] = false;
        }
        if (!("isActive" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isActive"] = false;
        }
        if (!("isLoggedIn" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isLoggedIn"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProfileInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileInfo(/** @type {Partial<ProfileInfo>} */($$parsedSource));
    }
}
